---

- name: Create group
  group:
    name: "{{ group_name }}"
    state: present

- name: Add user
  user:
    name: "{{ username }}"
    group: "{{ group_name }}"
    append: yes

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: check if cachet exists
  stat:
    path: /home/cachet/cachet-docker
  register: cachet_git

- name: clone cachet
  git:
    repo: "https://github.com/insight-icon/cachet-docker.git"
    dest: /home/cachet/cachet-docker
    version: v2.3.15
  become_user: cachet
  become: "yes"
  when: cachet_git.stat.exists == false

- name: Create cert directory if it does not exist
  file:
    path: /home/cachet/cachet-docker/certs
    state: directory
    mode: '0755'
    owner: cachet
    group: cachet

- name: Move cert to certs
  command: cp /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem /home/cachet/cachet-docker/certs/fullchain.pem

- name: Move key to certs
  command: cp /etc/letsencrypt/live/{{ fqdn }}/privkey.pem /home/cachet/cachet-docker/certs/privkey.pem

- name: Render the docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /home/cachet/cachet-docker/docker-compose.yml
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ group_name }}"

- name: copy the Dockerfile
  copy:
    src: Dockerfile
    dest: /home/cachet/cachet-docker/Dockerfile
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ group_name }}"

- name: copy dockerignore - muy importante
  copy:
    src: cachet.dockerignore
    dest: /home/cachet/cachet-docker/.dockerignore
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ group_name }}"

- name: Render the nginx file
  template:
    src: nginx-site.conf.j2
    dest: /home/cachet/cachet-docker/conf/nginx-site.conf
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ group_name }}"

- name: Copy over the env file
  copy:
    src: "{{ env_file | default('.env.defaults')}}"
    dest: /home/cachet/cachet-docker/.env
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ group_name }}"

- name: Copy service
  template:
    src: cachet.service.j2
    dest: /etc/systemd/system/cachet.service
    owner: root
    group: root
    mode: 0600

- name: Enable and start service
  systemd:
    name: cachet
    enabled: yes
    state: started
