- hosts: all
  roles:
    - { role: "dev-sec.os-hardening", when: ansible_hardening | default(false) | bool }
    - { role: "dev-sec.ssh-hardening", when: ansible_hardening | default(false) | bool }
    - { role: volumes, when: instance_store_enabled | default(false) | bool }
    - { role: "geerlingguy.php", when: cachet_local_build | default(false) | bool }
    - { role: "geerlingguy.git", when: cachet_local_build | default(false) | bool }
    - { role: "geerlingguy.composer", when: cachet_local_build | default(false) | bool }
    - common
    - role: geerlingguy.certbot
      become: yes
      certbot_create_if_missing: true
      certbot_admin_email: "webmaster@{{ fqdn }}"
      certbot_certs:
        - domains:
            - "{{ fqdn }}"
      certbot_create_standalone_stop_services: []

    - cachet
